import type { Guide } from "./schema";
import { calculateReadingTime, slugifyHeading } from "./utils";
import type { ContentBlock } from "./schema";

function guide(
  def: Omit<Guide, "type" | "readingTimeMinutes" | "chapters"> & { sections: ContentBlock[] },
): Guide {
  return {
    ...def,
    type: "guide",
    readingTimeMinutes: calculateReadingTime(def.sections, 500),
    chapters: def.sections
      .filter((b): b is Extract<ContentBlock, { type: "heading" }> => b.type === "heading" && b.level === 2)
      .map((b) => ({ title: b.text, id: slugifyHeading(b.text) })),
  };
}

export const guidesList: Guide[] = [
  guide({
    slug: "complete-erp-development-guide",
    title: "Complete ERP Development Guide",
    excerpt: "End-to-end ERP planning, module design, Tally integration, and rollout for manufacturing SMEs.",
    metaTitle: "Complete ERP Development Guide — Planning to Production",
    metaDescription: "Comprehensive ERP development guide: discovery, modules, Tally sync, shop-floor apps, and phased rollout.",
    publishedAt: "2026-01-01",
    updatedAt: "2026-02-01",
    authorId: "maxwell-team",
    category: "erp",
    tags: ["ERP", "Manufacturing", "Guide"],
    featured: true,
    downloadMagnetId: "erp-planning-template",
    sections: [
      { type: "paragraph", text: "Custom ERP is the operational backbone for manufacturers who've outgrown spreadsheets. This guide walks from discovery through production deployment—with GST and Tally integration built in." },
      { type: "heading", level: 2, text: "Chapter 1: Discovery & Process Mapping" },
      { type: "paragraph", text: "Spend two weeks on the shop floor before writing specs. Document material flow, approval chains, and exception handling." },
      { type: "list", items: ["Value stream mapping workshops", "Stakeholder interviews by role", "Integration inventory (Tally, logistics APIs)"] },
      { type: "heading", level: 2, text: "Chapter 2: Module Architecture" },
      { type: "paragraph", text: "Prioritize inventory → production → finance sync. Quality and maintenance modules follow once core ops are stable." },
      { type: "heading", level: 2, text: "Chapter 3: Tally & GST Integration" },
      { type: "paragraph", text: "Bi-directional sync with conflict resolution and audit logs. Never batch-only—finance needs near-real-time vouchers." },
      { type: "heading", level: 2, text: "Chapter 4: Rollout & Adoption" },
      { type: "paragraph", text: "Pilot one facility. Train champions. Measure adoption weekly—not just go-live date." },
      { type: "cta", title: "Download ERP Planning Template", description: "Get the companion spreadsheet with milestone planning.", href: "/resources/erp-readiness-checklist", label: "Get Template" },
    ],
    faqs: [{ question: "How long does custom ERP take?", answer: "MVP modules: 10–14 weeks. Multi-facility rollout: 4–6 months with phased deployment." }],
  }),
  guide({
    slug: "ai-implementation-guide",
    title: "AI Implementation Guide for Enterprise",
    excerpt: "From use-case selection through production MLOps—practical AI without pilot purgatory.",
    metaTitle: "AI Implementation Guide — Enterprise Deployment",
    metaDescription: "Enterprise AI implementation guide: use cases, RAG, vision AI, guardrails, and production MLOps.",
    publishedAt: "2025-12-01",
    updatedAt: "2026-01-15",
    authorId: "maxwell-team",
    category: "ai",
    tags: ["AI", "LLM", "Guide"],
    featured: true,
    downloadMagnetId: "ai-adoption-checklist",
    sections: [
      { type: "paragraph", text: "Enterprise AI succeeds when engineering discipline meets domain specificity—not when chatbots demo well in boardrooms." },
      { type: "heading", level: 2, text: "Use-Case Prioritization" },
      { type: "paragraph", text: "Score use cases on data availability, error cost, and automation potential. Start with high-volume, low-risk tasks." },
      { type: "heading", level: 2, text: "LLM & RAG Architecture" },
      { type: "paragraph", text: "Retrieval quality determines answer quality. Invest in chunking, metadata filters, and evaluation datasets." },
      { type: "heading", level: 2, text: "Computer Vision Deployment" },
      { type: "paragraph", text: "Train on facility-specific data. Edge deployment reduces latency for safety-critical alerts." },
      { type: "heading", level: 2, text: "Production & Monitoring" },
      { type: "paragraph", text: "Log prompts, outputs, and human overrides. Set drift alerts and quarterly model reviews." },
    ],
  }),
  guide({
    slug: "mobile-app-development-guide",
    title: "Mobile App Development Guide",
    excerpt: "Cross-platform strategy, offline sync, enterprise distribution, and launch playbook.",
    metaTitle: "Mobile App Development Guide — iOS & Android",
    metaDescription: "Complete mobile app development guide: React Native, Flutter, offline-first, App Store launch.",
    publishedAt: "2025-11-01",
    updatedAt: "2026-01-10",
    authorId: "maxwell-team",
    category: "mobile-apps",
    tags: ["Mobile", "React Native", "Guide"],
    sections: [
      { type: "paragraph", text: "Mobile apps for field teams, patients, and customers require offline resilience and enterprise-grade security—not consumer-app shortcuts." },
      { type: "heading", level: 2, text: "Platform Selection" },
      { type: "paragraph", text: "React Native for JS-heavy teams; Flutter for pixel-perfect UI. Native only when hardware APIs dominate." },
      { type: "heading", level: 2, text: "Offline-First Design" },
      { type: "paragraph", text: "Local persistence, sync queues, and conflict resolution patterns for unreliable networks." },
      { type: "heading", level: 2, text: "Launch & Distribution" },
      { type: "paragraph", text: "App Store compliance, MDM for enterprise, and analytics instrumentation from day one." },
    ],
  }),
  guide({
    slug: "custom-software-development-guide",
    title: "Custom Software Development Guide",
    excerpt: "Architecture, team structure, delivery methodology, and IP ownership for bespoke platforms.",
    metaTitle: "Custom Software Development Guide",
    metaDescription: "Custom software development guide: architecture, Agile delivery, documentation, and IP ownership.",
    publishedAt: "2025-10-01",
    updatedAt: "2026-01-20",
    authorId: "maxwell-team",
    category: "software-development",
    tags: ["Custom Software", "Guide"],
    featured: true,
    sections: [
      { type: "paragraph", text: "Custom software captures competitive workflows. This guide covers how to partner with engineering teams for predictable delivery." },
      { type: "heading", level: 2, text: "Requirements & Discovery" },
      { type: "paragraph", text: "User stories tied to business metrics—not feature wishlists. Prototype critical flows before full build." },
      { type: "heading", level: 2, text: "Technical Architecture" },
      { type: "paragraph", text: "Modular monolith for early stage; microservices when team and scale justify operational complexity." },
      { type: "heading", level: 2, text: "Delivery & QA" },
      { type: "paragraph", text: "Two-week sprints, demo-driven reviews, automated tests on critical paths." },
    ],
  }),
  guide({
    slug: "saas-development-guide",
    title: "SaaS Development Guide",
    excerpt: "Multi-tenant architecture, Stripe billing, admin dashboards, and investor-ready MVPs.",
    metaTitle: "SaaS Development Guide — MVP to Scale",
    metaDescription: "SaaS development guide: multi-tenancy, billing, admin panels, and scaling architecture.",
    publishedAt: "2025-12-10",
    updatedAt: "2026-02-05",
    authorId: "maxwell-team",
    category: "saas",
    tags: ["SaaS", "Startup", "Guide"],
    sections: [
      { type: "paragraph", text: "SaaS products need tenancy, billing, and observability from MVP—not as Series A afterthoughts." },
      { type: "heading", level: 2, text: "Multi-Tenant Data Model" },
      { type: "paragraph", text: "tenant_id on all rows; RBAC within tenant; super-admin for support impersonation with audit logs." },
      { type: "heading", level: 2, text: "Subscription Billing" },
      { type: "paragraph", text: "Stripe webhooks with idempotency keys. Handle failed payments, upgrades, and proration." },
      { type: "heading", level: 2, text: "Scaling Path" },
      { type: "paragraph", text: "Read replicas, queue workers, and feature flags before premature Kubernetes complexity." },
    ],
  }),
  guide({
    slug: "crm-implementation-playbook",
    title: "CRM Implementation Playbook",
    excerpt: "Pipeline design, data migration, automation, and adoption for B2B sales teams.",
    metaTitle: "CRM Implementation Playbook — B2B Sales",
    metaDescription: "CRM implementation playbook: pipeline design, migration, automation, and team adoption.",
    publishedAt: "2025-11-15",
    updatedAt: "2026-01-05",
    authorId: "maxwell-team",
    category: "crm",
    tags: ["CRM", "Guide"],
    downloadMagnetId: "crm-selection-framework",
    sections: [
      { type: "paragraph", text: "CRM succeeds when it mirrors how your team actually sells—not how Salesforce assumes you sell." },
      { type: "heading", level: 2, text: "Pipeline Design" },
      { type: "paragraph", text: "Custom stages, required fields per stage, and approval workflows for discounts and samples." },
      { type: "heading", level: 2, text: "Migration & Data Quality" },
      { type: "paragraph", text: "Dedupe contacts, normalize company names, and map legacy fields before import." },
    ],
  }),
  guide({
    slug: "cloud-migration-guide",
    title: "Cloud Migration Guide",
    excerpt: "AWS/Azure assessment, phased migration, IaC, and FinOps for production workloads.",
    metaTitle: "Cloud Migration Guide — AWS & Azure",
    metaDescription: "Cloud migration guide: assessment, phased cutover, Terraform IaC, and cost optimization.",
    publishedAt: "2025-10-25",
    updatedAt: "2025-12-20",
    authorId: "maxwell-team",
    category: "cloud",
    tags: ["Cloud", "AWS", "Guide"],
    sections: [
      { type: "paragraph", text: "Cloud migration is architecture modernization—not datacenter lift-and-shift." },
      { type: "heading", level: 2, text: "Assessment" },
      { type: "paragraph", text: "Map dependencies, compliance, and RTO/RPO requirements per workload." },
      { type: "heading", level: 2, text: "Migration Waves" },
      { type: "paragraph", text: "Non-critical dev/staging first; customer-facing APIs with blue-green cutover." },
    ],
  }),
  guide({
    slug: "website-strategy-guide",
    title: "Website Strategy Guide for B2B Growth",
    excerpt: "SEO architecture, content hubs, conversion paths, and analytics for lead generation.",
    metaTitle: "B2B Website Strategy Guide",
    metaDescription: "B2B website strategy guide: SEO hubs, conversion paths, analytics, and content architecture.",
    publishedAt: "2026-01-12",
    updatedAt: "2026-02-10",
    authorId: "maxwell-team",
    category: "web-development",
    tags: ["Website", "SEO", "Guide"],
    sections: [
      { type: "paragraph", text: "Your website is the highest-leverage sales asset. Strategy connects SEO content, case studies, and conversion tools." },
      { type: "heading", level: 2, text: "Content Hub Architecture" },
      { type: "paragraph", text: "Services, industries, locations, and blog interlink for topical authority." },
      { type: "heading", level: 2, text: "Conversion Stack" },
      { type: "paragraph", text: "Estimators, consultation booking, and WhatsApp for high-intent visitors." },
    ],
  }),
  guide({
    slug: "devops-cicd-guide",
    title: "DevOps & CI/CD Guide for Software Teams",
    excerpt: "Pipeline design, testing gates, staging environments, and deployment automation.",
    metaTitle: "DevOps CI/CD Guide for Enterprise Teams",
    metaDescription: "DevOps and CI/CD guide: pipelines, testing, staging, and deployment automation best practices.",
    publishedAt: "2025-09-15",
    updatedAt: "2025-12-01",
    authorId: "maxwell-team",
    category: "cloud",
    tags: ["DevOps", "CI/CD", "Guide"],
    sections: [
      { type: "paragraph", text: "Deployment friction kills velocity. CI/CD with automated tests on critical paths enables weekly releases safely." },
      { type: "heading", level: 2, text: "Pipeline Stages" },
      { type: "list", items: ["Lint + unit tests on PR", "Integration tests on merge", "Staging deploy + smoke tests", "Production with approval gate"] },
    ],
  }),
  guide({
    slug: "digital-transformation-playbook",
    title: "Digital Transformation Playbook",
    excerpt: "12-month roadmap template, governance, and ROI measurement for enterprise modernization.",
    metaTitle: "Digital Transformation Playbook",
    metaDescription: "Digital transformation playbook: roadmap, governance, change management, and ROI tracking.",
    publishedAt: "2025-08-01",
    updatedAt: "2026-01-30",
    authorId: "maxwell-team",
    category: "digital-transformation",
    tags: ["Transformation", "Strategy", "Guide"],
    downloadMagnetId: "digital-transformation-roadmap",
    sections: [
      { type: "paragraph", text: "Transformation is a sequence of bets—with governance ensuring each phase earns the next investment." },
      { type: "heading", level: 2, text: "Governance Model" },
      { type: "paragraph", text: "Executive sponsor, cross-functional steering committee, and monthly ROI reviews." },
      { type: "heading", level: 2, text: "Technology Sequence" },
      { type: "paragraph", text: "Visibility → core systems → automation → intelligence. Never skip data quality gates." },
    ],
  }),
];

export const guideSlugs = guidesList.map((g) => g.slug);
export const guidesMap = Object.fromEntries(guidesList.map((g) => [g.slug, g]));

export function getGuideBySlug(slug: string): Guide | undefined {
  return guidesMap[slug];
}

export function getAllGuides(): Guide[] {
  return guidesList;
}
