import type { Resource } from "./schema";
import { calculateReadingTime } from "./utils";

function resource(
  def: Omit<Resource, "type" | "readingTimeMinutes">,
): Resource {
  return {
    ...def,
    type: "resource",
    readingTimeMinutes: calculateReadingTime(def.previewSections, 200),
  };
}

export const resourcesList: Resource[] = [
  resource({
    slug: "erp-readiness-checklist",
    title: "ERP Readiness Checklist",
    excerpt: "25-point assessment to validate your organization is ready for ERP development.",
    metaTitle: "ERP Readiness Checklist — Free Download",
    metaDescription: "Free ERP readiness checklist: 25 assessment points before starting custom ERP development.",
    publishedAt: "2026-01-05",
    updatedAt: "2026-01-05",
    authorId: "maxwell-team",
    category: "erp",
    tags: ["ERP", "Checklist", "Download"],
    featured: true,
    resourceType: "checklist",
    format: "PDF · 8 pages",
    pageCount: 8,
    gated: true,
    downloadMagnetId: "erp-readiness-checklist",
    benefits: ["Identify gaps before RFP", "Align stakeholders", "Estimate timeline realistically"],
    previewSections: [
      { type: "paragraph", text: "Use this checklist in executive workshops before committing to ERP budget. Each item includes evaluation criteria and common failure modes." },
      { type: "heading", level: 2, text: "What's inside" },
      { type: "list", items: ["Process documentation maturity", "Data quality assessment", "Integration requirements", "Change management readiness", "Budget and timeline realism"] },
    ],
  }),
  resource({
    slug: "crm-implementation-guide",
    title: "CRM Implementation Guide (PDF)",
    excerpt: "Phase-by-phase CRM rollout playbook for B2B sales organizations.",
    metaTitle: "CRM Implementation Guide — Free PDF",
    metaDescription: "Download CRM implementation guide: phases, migration, automation, and adoption for B2B teams.",
    publishedAt: "2025-12-01",
    updatedAt: "2025-12-01",
    authorId: "maxwell-team",
    category: "crm",
    tags: ["CRM", "PDF"],
    resourceType: "guide-pdf",
    format: "PDF · 24 pages",
    pageCount: 24,
    gated: true,
    downloadMagnetId: "crm-implementation-guide",
    benefits: ["Pipeline templates", "Migration checklist", "Automation recipes"],
    previewSections: [
      { type: "paragraph", text: "Structured rollout from pipeline design through go-live—with adoption metrics at each phase." },
    ],
  }),
  resource({
    slug: "ai-adoption-framework",
    title: "AI Adoption Framework",
    excerpt: "Use-case scoring matrix and pilot-to-production checklist for enterprise AI.",
    metaTitle: "AI Adoption Framework — Free Download",
    metaDescription: "AI adoption framework: use-case scoring, pilot checklist, and production readiness gates.",
    publishedAt: "2026-02-01",
    updatedAt: "2026-02-01",
    authorId: "maxwell-team",
    category: "ai",
    tags: ["AI", "Framework"],
    trending: true,
    resourceType: "framework",
    format: "PDF · 16 pages",
    pageCount: 16,
    gated: true,
    downloadMagnetId: "ai-adoption-framework",
    benefits: ["Prioritize high-ROI use cases", "Avoid pilot purgatory", "Executive reporting template"],
    previewSections: [
      { type: "paragraph", text: "Score AI opportunities on data readiness, error cost, and automation potential before allocating budget." },
    ],
  }),
  resource({
    slug: "website-planning-checklist",
    title: "Website Planning Checklist",
    excerpt: "Discovery questions for high-converting B2B websites and RFP preparation.",
    metaTitle: "Website Planning Checklist — Free Download",
    metaDescription: "Website planning checklist for B2B: discovery questions, SEO, conversion, and technical requirements.",
    publishedAt: "2025-11-20",
    updatedAt: "2025-11-20",
    authorId: "maxwell-team",
    category: "web-development",
    tags: ["Website", "Checklist"],
    resourceType: "checklist",
    format: "PDF · 6 pages",
    gated: true,
    downloadMagnetId: "website-planning-checklist",
    benefits: ["Clear RFP requirements", "SEO and performance specs", "Conversion path mapping"],
    previewSections: [
      { type: "paragraph", text: "Answer these questions before engaging a development partner—or use internally to align marketing and engineering." },
    ],
  }),
  resource({
    slug: "software-vendor-selection-guide",
    title: "Software Vendor Selection Guide",
    excerpt: "RFP criteria, scorecard template, and due diligence questions for offshore partners.",
    metaTitle: "Software Vendor Selection Guide",
    metaDescription: "Software vendor selection guide: RFP template, scorecard, and due diligence for development partners.",
    publishedAt: "2025-10-10",
    updatedAt: "2025-10-10",
    authorId: "maxwell-team",
    category: "software-development",
    tags: ["Vendor", "RFP"],
    resourceType: "guide-pdf",
    format: "PDF · 18 pages",
    gated: true,
    downloadMagnetId: "vendor-selection-guide",
    benefits: ["Objective vendor comparison", "IP and contract checklist", "Reference call scripts"],
    previewSections: [
      { type: "paragraph", text: "Avoid costly vendor mistakes with structured evaluation across technical, delivery, and commercial dimensions." },
    ],
  }),
  resource({
    slug: "saas-metrics-template",
    title: "SaaS Metrics Dashboard Template",
    excerpt: "MRR, churn, LTV, and cohort tracking spreadsheet for early-stage SaaS.",
    metaTitle: "SaaS Metrics Template — Free Download",
    metaDescription: "SaaS metrics dashboard template: MRR, churn, LTV, cohort analysis for startups.",
    publishedAt: "2025-12-15",
    updatedAt: "2025-12-15",
    authorId: "maxwell-team",
    category: "saas",
    tags: ["SaaS", "Metrics"],
    resourceType: "template",
    format: "XLSX",
    gated: true,
    downloadMagnetId: "software-cost-calculator",
    benefits: ["Investor-ready metrics", "Cohort analysis", "Churn tracking"],
    previewSections: [
      { type: "paragraph", text: "Pre-built formulas for Indian SaaS startups tracking INR revenue and GST separately." },
    ],
  }),
  resource({
    slug: "mobile-app-spec-template",
    title: "Mobile App Specification Template",
    excerpt: "User stories, screen flows, and API requirements template for app projects.",
    metaTitle: "Mobile App Spec Template",
    metaDescription: "Mobile app specification template: user stories, flows, offline requirements, API specs.",
    publishedAt: "2025-11-01",
    updatedAt: "2025-11-01",
    authorId: "maxwell-team",
    category: "mobile-apps",
    tags: ["Mobile", "Template"],
    resourceType: "template",
    format: "PDF · 12 pages",
    gated: true,
    downloadMagnetId: "software-cost-calculator",
    benefits: ["Clear dev scope", "Offline requirements section", "App Store checklist"],
    previewSections: [
      { type: "paragraph", text: "Standardize mobile project kickoffs with screens, permissions, and sync requirements documented upfront." },
    ],
  }),
  resource({
    slug: "cloud-cost-worksheet",
    title: "Cloud Cost Planning Worksheet",
    excerpt: "AWS/Azure monthly cost estimator with rightsizing recommendations.",
    metaTitle: "Cloud Cost Worksheet — Free Download",
    metaDescription: "Cloud cost planning worksheet for AWS and Azure workloads—estimation and optimization.",
    publishedAt: "2025-10-05",
    updatedAt: "2025-10-05",
    authorId: "maxwell-team",
    category: "cloud",
    tags: ["Cloud", "FinOps"],
    resourceType: "template",
    format: "XLSX",
    gated: true,
    downloadMagnetId: "software-cost-calculator",
    benefits: ["Budget forecasting", "Rightsizing flags", "Reserved instance calculator"],
    previewSections: [
      { type: "paragraph", text: "Model production, staging, and dev environments before cloud commit—or audit existing spend." },
    ],
  }),
  resource({
    slug: "security-audit-checklist",
    title: "Application Security Audit Checklist",
    excerpt: "OWASP-aligned checklist for web and mobile app security reviews.",
    metaTitle: "Security Audit Checklist for Applications",
    metaDescription: "Application security audit checklist—OWASP, auth, API security for enterprise apps.",
    publishedAt: "2025-09-20",
    updatedAt: "2025-09-20",
    authorId: "maxwell-team",
    category: "software-development",
    tags: ["Security", "Checklist"],
    resourceType: "checklist",
    format: "PDF · 14 pages",
    gated: true,
    downloadMagnetId: "software-cost-calculator",
    benefits: ["Pre-launch security review", "Compliance prep", "Vendor assessment"],
    previewSections: [
      { type: "paragraph", text: "Run before production launch or annual security reviews. Covers auth, APIs, data handling, and infrastructure." },
    ],
  }),
  resource({
    slug: "erp-buyers-guide",
    title: "ERP Buyer's Guide",
    excerpt: "Executive guide to evaluating custom ERP vs off-the-shelf for Indian manufacturers and distributors.",
    metaTitle: "ERP Buyer's Guide — Free Download",
    metaDescription: "ERP buyer's guide: build vs buy, Tally integration, GST compliance, and vendor evaluation for Indian SMEs.",
    publishedAt: "2026-03-01",
    updatedAt: "2026-03-01",
    authorId: "maxwell-team",
    category: "erp",
    tags: ["ERP", "Buyer's Guide", "Download"],
    featured: true,
    resourceType: "guide-pdf",
    format: "PDF · 28 pages",
    pageCount: 28,
    gated: true,
    downloadMagnetId: "erp-readiness-checklist",
    benefits: ["Build vs buy framework", "Module checklist", "TCO comparison worksheet"],
    previewSections: [
      { type: "paragraph", text: "Use before RFP or vendor meetings. Covers Indian compliance, Tally integration, and realistic cost ranges for mid-market ERP." },
    ],
  }),
  resource({
    slug: "crm-implementation-checklist",
    title: "CRM Implementation Checklist",
    excerpt: "Step-by-step CRM rollout checklist for B2B sales teams—pipeline, migration, automation, adoption.",
    metaTitle: "CRM Implementation Checklist — Free Download",
    metaDescription: "CRM implementation checklist for B2B: pipeline design, data migration, automation, and user adoption.",
    publishedAt: "2026-03-01",
    updatedAt: "2026-03-01",
    authorId: "maxwell-team",
    category: "crm",
    tags: ["CRM", "Checklist"],
    resourceType: "checklist",
    format: "PDF · 10 pages",
    gated: true,
    downloadMagnetId: "crm-implementation-guide",
    benefits: ["Go-live readiness gates", "Migration validation", "Adoption scorecard"],
    previewSections: [
      { type: "paragraph", text: "Phase-by-phase checklist from pipeline design through hypercare—used in Maxwell CRM rollouts." },
    ],
  }),
  resource({
    slug: "digital-transformation-roadmap-template",
    title: "Digital Transformation Roadmap",
    excerpt: "Phased modernization template for operations, ERP, CRM, and automation investments.",
    metaTitle: "Digital Transformation Roadmap Template",
    metaDescription: "Digital transformation roadmap template—phased ERP, CRM, automation plan for Indian enterprises.",
    publishedAt: "2026-02-15",
    updatedAt: "2026-02-15",
    authorId: "maxwell-team",
    category: "digital-transformation",
    tags: ["Roadmap", "Template"],
    trending: true,
    resourceType: "template",
    format: "PDF · 14 pages",
    gated: true,
    downloadMagnetId: "digital-transformation-roadmap",
    benefits: ["12-month phased plan", "Investment prioritization", "Executive presentation slides"],
    previewSections: [
      { type: "paragraph", text: "Prioritize ERP, CRM, and automation in the right sequence—with budget and timeline placeholders." },
    ],
  }),
  resource({
    slug: "automation-assessment-template",
    title: "Automation Assessment Template",
    excerpt: "Score manual processes for automation ROI—workflows, hours saved, and error cost.",
    metaTitle: "Automation Assessment Template — Free Download",
    metaDescription: "Business process automation assessment template—ROI scoring for manual workflows.",
    publishedAt: "2026-02-01",
    updatedAt: "2026-02-01",
    authorId: "maxwell-team",
    category: "software-development",
    tags: ["Automation", "Assessment"],
    resourceType: "template",
    format: "XLSX + PDF",
    gated: true,
    downloadMagnetId: "software-cost-calculator",
    benefits: ["Process scoring matrix", "ROI calculator", "Prioritization ranking"],
    previewSections: [
      { type: "paragraph", text: "Identify which manual processes to automate first—used in discovery workshops with operations heads." },
    ],
  }),
  resource({
    slug: "software-rfp-template",
    title: "Software Development RFP Template",
    excerpt: "Request for proposal template with technical, commercial, and delivery sections.",
    metaTitle: "Software Development RFP Template",
    metaDescription: "Software RFP template for custom development projects—technical and commercial sections.",
    publishedAt: "2025-08-25",
    updatedAt: "2025-08-25",
    authorId: "maxwell-team",
    category: "software-development",
    tags: ["RFP", "Template"],
    resourceType: "template",
    format: "DOCX/PDF",
    gated: true,
    downloadMagnetId: "vendor-selection-guide",
    benefits: ["Consistent vendor comparison", "Scope clarity", "SLA definitions"],
    previewSections: [
      { type: "paragraph", text: "Issue structured RFPs that attract quality responses—with sections for integrations, IP, and support SLAs." },
    ],
  }),
];

export const resourceSlugs = resourcesList.map((r) => r.slug);
export const resourcesMap = Object.fromEntries(resourcesList.map((r) => [r.slug, r]));

export function getResourceBySlug(slug: string): Resource | undefined {
  return resourcesMap[slug];
}

export function getAllResources(): Resource[] {
  return resourcesList;
}
