import type { ToolCategory, ToolDefinition } from "./types";

export const toolCategoryLabels: Record<ToolCategory, string> = {
  planning: "Planning & Delivery",
  sales: "Sales & Proposals",
  technical: "Technical Advisory",
  finance: "Cost & ROI",
  strategy: "Strategy & Assessment",
};

export const toolsRegistry: ToolDefinition[] = [
  {
    slug: "project-roadmap",
    name: "Project Roadmap Generator",
    shortName: "Roadmap",
    description: "Generate phased roadmaps with milestones, deliverables, and timeline based on your project constraints.",
    category: "planning",
    icon: "roadmap",
    accent: "#2563EB",
    featured: true,
    popular: true,
    recentlyUpdated: true,
    estimatedMinutes: 4,
    tags: ["roadmap", "milestones", "planning"],
  },
  {
    slug: "proposal-generator",
    name: "Proposal Generator",
    shortName: "Proposal",
    description: "Build professional client proposals with scope, stack recommendations, timeline, and investment range.",
    category: "sales",
    icon: "proposal",
    accent: "#8B5CF6",
    featured: true,
    popular: true,
    estimatedMinutes: 5,
    tags: ["proposal", "scope", "client"],
  },
  {
    slug: "rfp-builder",
    name: "RFP Builder",
    shortName: "RFP",
    description: "Create structured Request for Proposal documents with objectives, requirements, and evaluation criteria.",
    category: "sales",
    icon: "rfp",
    accent: "#06B6D4",
    recentlyUpdated: true,
    estimatedMinutes: 6,
    tags: ["RFP", "requirements", "vendor"],
  },
  {
    slug: "tech-stack-advisor",
    name: "Tech Stack Advisor",
    shortName: "Tech Stack",
    description: "Get tailored frontend, backend, database, and cloud recommendations for your scale and budget.",
    category: "technical",
    icon: "stack",
    accent: "#10B981",
    featured: true,
    estimatedMinutes: 3,
    tags: ["architecture", "stack", "cloud"],
  },
  {
    slug: "software-cost-calculator",
    name: "Software Cost Calculator",
    shortName: "Cost Calculator",
    description: "Advanced estimate including features, compliance, integrations, team composition, and timeline.",
    category: "finance",
    icon: "calculator",
    accent: "#F59E0B",
    popular: true,
    recentlyUpdated: true,
    estimatedMinutes: 5,
    tags: ["cost", "estimate", "budget"],
  },
  {
    slug: "digital-transformation-assessment",
    name: "Digital Transformation Assessment",
    shortName: "DX Assessment",
    description: "Measure digital maturity and receive improvement opportunities with a suggested modernization roadmap.",
    category: "strategy",
    icon: "assessment",
    accent: "#1A4B8C",
    featured: true,
    estimatedMinutes: 4,
    tags: ["maturity", "transformation", "assessment"],
  },
  {
    slug: "roi-calculator",
    name: "ROI Calculator",
    shortName: "ROI",
    description: "Model potential savings, productivity gains, payback period, and ROI from process automation.",
    category: "finance",
    icon: "roi",
    accent: "#6366F1",
    popular: true,
    estimatedMinutes: 3,
    tags: ["ROI", "savings", "automation"],
  },
  {
    slug: "erp-roi-calculator",
    name: "ERP ROI Calculator",
    shortName: "ERP ROI",
    description: "Calculate ERP payback period, inventory savings, and 5-year ROI for manufacturing and distribution SMEs.",
    category: "finance",
    icon: "roi",
    accent: "#1A4B8C",
    featured: true,
    popular: true,
    estimatedMinutes: 4,
    tags: ["ERP ROI", "ERP payback", "manufacturing ERP", "ERP cost savings"],
  },
  {
    slug: "crm-roi-calculator",
    name: "CRM ROI Calculator",
    shortName: "CRM ROI",
    description: "Estimate CRM payback from pipeline efficiency, faster follow-ups, and reduced lead leakage.",
    category: "finance",
    icon: "roi",
    accent: "#8B5CF6",
    featured: true,
    popular: true,
    estimatedMinutes: 4,
    tags: ["CRM ROI", "sales CRM", "pipeline ROI", "CRM payback"],
  },
  {
    slug: "ai-readiness-assessment",
    name: "AI Readiness Assessment",
    shortName: "AI Readiness",
    description: "Score your data, infrastructure, and governance readiness for practical AI pilots with a phased action plan.",
    category: "strategy",
    icon: "assessment",
    accent: "#EC4899",
    featured: true,
    popular: true,
    estimatedMinutes: 5,
    tags: ["AI readiness", "AI assessment", "machine learning", "AI strategy"],
  },
  {
    slug: "vendor-comparison-scorecard",
    name: "Vendor Comparison Scorecard",
    shortName: "Vendor Scorecard",
    description: "Compare up to 3 software vendors on experience, pricing, timeline, and support—with a weighted recommendation.",
    category: "sales",
    icon: "rfp",
    accent: "#06B6D4",
    featured: true,
    estimatedMinutes: 6,
    tags: ["vendor comparison", "RFP evaluation", "software vendor", "scorecard"],
  },
  {
    slug: "erp-requirement-generator",
    name: "ERP Requirement Generator",
    shortName: "ERP Requirements",
    description: "Generate structured ERP functional, technical, and integration requirements for vendor RFPs and internal alignment.",
    category: "sales",
    icon: "rfp",
    accent: "#1A4B8C",
    popular: true,
    estimatedMinutes: 5,
    tags: ["ERP requirements", "ERP RFP", "ERP modules", "ERP specification"],
  },
  {
    slug: "crm-requirement-generator",
    name: "CRM Requirement Generator",
    shortName: "CRM Requirements",
    description: "Build CRM pipeline, automation, and integration requirements tailored to your sales process and team size.",
    category: "sales",
    icon: "proposal",
    accent: "#8B5CF6",
    popular: true,
    estimatedMinutes: 5,
    tags: ["CRM requirements", "sales CRM", "pipeline design", "CRM RFP"],
  },
  {
    slug: "project-timeline-estimator",
    name: "Project Timeline Estimator",
    shortName: "Timeline Estimator",
    description: "Estimate realistic delivery timelines for ERP, CRM, mobile, and custom software based on scope and integrations.",
    category: "planning",
    icon: "roadmap",
    accent: "#2563EB",
    featured: true,
    recentlyUpdated: true,
    estimatedMinutes: 4,
    tags: ["project timeline", "delivery estimate", "software schedule", "go-live date"],
  },
  {
    slug: "team-size-calculator",
    name: "Team Size Calculator",
    shortName: "Team Calculator",
    description: "Calculate recommended PM, dev, QA, and design headcount for your software project scope and timeline.",
    category: "planning",
    icon: "roadmap",
    accent: "#10B981",
    popular: true,
    estimatedMinutes: 3,
    tags: ["team size", "staffing", "development team", "project resources"],
  },
];

export const toolSlugs = toolsRegistry.map((t) => t.slug);

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return toolsRegistry.find((t) => t.slug === slug);
}

export function getFeaturedTools(): ToolDefinition[] {
  return toolsRegistry.filter((t) => t.featured);
}

export function getPopularTools(): ToolDefinition[] {
  return toolsRegistry.filter((t) => t.popular);
}

export function getRecentlyUpdatedTools(): ToolDefinition[] {
  return toolsRegistry.filter((t) => t.recentlyUpdated);
}
