import type {
  CityCatalogEntry,
  CompareTemplate,
  CountryCatalogEntry,
  IndustryCatalogEntry,
  ServiceCatalogEntry,
} from "./types";

export const programmaticServices: ServiceCatalogEntry[] = [
  {
    key: "erp",
    slug: "erp-development",
    label: "ERP Development",
    shortLabel: "ERP",
    solutionSlug: "erp-development-company",
    serviceHref: "/services/erp-development",
    description: "Custom ERP for inventory, production, finance, GST, and Tally integration.",
    costRangeInr: "₹8L – ₹45L+",
    costRangeUsd: "$15K – $80K+",
    technologies: ["React", "Node.js", "PostgreSQL", "Redis", "AWS"],
  },
  {
    key: "crm",
    slug: "crm-development",
    label: "CRM Development",
    shortLabel: "CRM",
    solutionSlug: "crm-development-company",
    serviceHref: "/services/crm-development",
    description: "Sales CRM, distributor CRM, and field-force apps tailored to your pipeline.",
    costRangeInr: "₹5L – ₹25L+",
    costRangeUsd: "$10K – $45K+",
    technologies: ["React", "Node.js", "PostgreSQL", "AWS"],
  },
  {
    key: "ai",
    slug: "ai-development",
    label: "AI Development",
    shortLabel: "AI",
    solutionSlug: "ai-development-company-india",
    serviceHref: "/services/ai-solutions",
    description: "Industrial AI, computer vision, LLM automation, and predictive analytics.",
    costRangeInr: "₹6L – ₹35L+",
    costRangeUsd: "$12K – $60K+",
    technologies: ["Python", "FastAPI", "OpenCV", "React", "AWS"],
  },
  {
    key: "mobile",
    slug: "mobile-app-development",
    label: "Mobile App Development",
    shortLabel: "Mobile Apps",
    solutionSlug: "mobile-app-development-company",
    serviceHref: "/services/mobile-app-development",
    description: "Flutter and React Native apps for field teams, shop floors, and consumer products.",
    costRangeInr: "₹4L – ₹30L+",
    costRangeUsd: "$8K – $55K+",
    technologies: ["Flutter", "React Native", "Node.js", "Firebase"],
  },
  {
    key: "web",
    slug: "web-development",
    label: "Web Development",
    shortLabel: "Web Apps",
    solutionSlug: "website-development-company",
    serviceHref: "/services/website-development",
    description: "Next.js websites and web applications with Core Web Vitals 95+ scores.",
    costRangeInr: "₹2L – ₹20L+",
    costRangeUsd: "$4K – $35K+",
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
  },
  {
    key: "software",
    slug: "custom-software-development",
    label: "Custom Software Development",
    shortLabel: "Custom Software",
    solutionSlug: "custom-software-development-company",
    serviceHref: "/services/custom-software-development",
    description: "Bespoke business applications engineered around your unique workflows.",
    costRangeInr: "₹6L – ₹50L+",
    costRangeUsd: "$12K – $90K+",
    technologies: ["React", "Node.js", "Python", "PostgreSQL", "AWS"],
  },
  {
    key: "automation",
    slug: "business-automation",
    label: "Business Automation",
    shortLabel: "Automation",
    solutionSlug: "business-automation-services",
    serviceHref: "/services/custom-software-development",
    description: "Workflow automation, approval chains, and integration between business systems.",
    costRangeInr: "₹3L – ₹18L+",
    costRangeUsd: "$6K – $30K+",
    technologies: ["Node.js", "Python", "PostgreSQL", "Zapier-style APIs"],
  },
  {
    key: "dx",
    slug: "digital-transformation",
    label: "Digital Transformation",
    shortLabel: "Digital Transformation",
    solutionSlug: "digital-transformation-company",
    serviceHref: "/services/custom-software-development",
    description: "Legacy modernization, cloud migration, and enterprise digitization roadmaps.",
    costRangeInr: "₹10L – ₹60L+",
    costRangeUsd: "$20K – $100K+",
    technologies: ["Cloud", "React", "Node.js", "Data pipelines"],
  },
];

export const programmaticIndustries: IndustryCatalogEntry[] = [
  { slug: "manufacturing", name: "Manufacturing", focus: "discrete and process manufacturing", painPoints: ["shop-floor visibility gaps", "inventory inaccuracy", "production planning in spreadsheets"], compliance: "ISO, factory regulations, GST e-invoicing", icon: "factory" },
  { slug: "chemical", name: "Chemical", focus: "batch manufacturing and specialty chemicals", painPoints: ["batch traceability", "MSDS compliance", "reactor scheduling conflicts"], compliance: "MSDS, REACH-style documentation, batch records", icon: "factory" },
  { slug: "chemical-manufacturing", name: "Chemical Manufacturing", focus: "CRM and ERP for chemical manufacturers and distributors", painPoints: ["batch traceability gaps", "SDS documentation chaos", "hazmat storage compliance"], compliance: "MSDS, batch records, GST e-invoicing", icon: "factory" },
  { slug: "pharma", name: "Pharma", focus: "formulations and API manufacturing", painPoints: ["GMP batch records", "expiry tracking", "regulatory audit trails"], compliance: "GMP, WHO-GMP, Schedule M alignment", icon: "health" },
  { slug: "textile", name: "Textile", focus: "spinning, weaving, dyeing, and garment units", painPoints: ["fabric inventory chaos", "job-work tracking", "seasonal order spikes"], compliance: "GST, export documentation, quality norms", icon: "factory" },
  { slug: "automotive", name: "Automotive Components", focus: "auto parts and tier-2 suppliers", painPoints: ["OEM delivery schedules", "tool cavity tracking", "supplier quality audits"], compliance: "IATF-style traceability, PPAP documentation", icon: "factory" },
  { slug: "fmcg", name: "FMCG", focus: "distribution and consumer goods", painPoints: ["route sales visibility", "distributor claims", "scheme management"], compliance: "GST, FSSAI where applicable", icon: "retail" },
  { slug: "metals", name: "Metals & Steel", focus: "rolling mills and metal processing", painPoints: ["coil weight tracking", "melt shop planning", "quality certificates"], compliance: "mill test certificates, GST", icon: "factory" },
  { slug: "plastics", name: "Plastics", focus: "injection molding and extrusion", painPoints: ["mold maintenance cycles", "regrind tracking", "cycle time optimization"], compliance: "quality inspection records", icon: "factory" },
  { slug: "food-processing", name: "Food Processing", focus: "packaged foods and processing plants", painPoints: ["batch traceability", "cold chain gaps", "FSSAI documentation"], compliance: "FSSAI, HACCP-style records", icon: "factory" },
  { slug: "healthcare", name: "Healthcare", focus: "hospitals and healthcare networks", painPoints: ["patient flow bottlenecks", "billing reconciliation", "multi-location reporting"], compliance: "data privacy, clinical audit trails", icon: "health" },
  { slug: "logistics", name: "Logistics", focus: "3PL, fleet, and warehouse operations", painPoints: ["dispatch delays", "POD reconciliation", "warehouse slotting"], compliance: "e-way bill integration, GST", icon: "logistics" },
  { slug: "retail", name: "Retail", focus: "retail chains and omnichannel", painPoints: ["stock-outs", "POS reconciliation", "loyalty fragmentation"], compliance: "GST, PCI-aware payments", icon: "retail" },
  { slug: "construction", name: "Construction", focus: "builders and contractors", painPoints: ["project cost overruns", "site reporting delays", "subcontractor billing"], compliance: "RERA-aware project tracking", icon: "construction" },
  { slug: "education", name: "Education", focus: "schools and training institutes", painPoints: ["fee collection gaps", "parent communication", "exam scheduling"], compliance: "student data privacy", icon: "education" },
  { slug: "education-data-privacy", name: "Education Data Privacy", focus: "DPDP-aligned student data governance and EMS", painPoints: ["student PII sprawl", "weak access controls", "EdTech vendor sprawl"], compliance: "DPDP Act, student data privacy", icon: "education" },
  { slug: "oil-gas", name: "Oil & Gas", focus: "downstream and equipment suppliers", painPoints: ["maintenance scheduling", "safety compliance", "asset lifecycle tracking"], compliance: "safety audit documentation", icon: "factory" },
  { slug: "energy", name: "Energy", focus: "power equipment and renewables", painPoints: ["project commissioning delays", "O&M ticket backlog", "spares inventory"], compliance: "grid and safety documentation", icon: "factory" },
  { slug: "agriculture", name: "Agriculture", focus: "agro-processing and agri-input", painPoints: ["procurement seasonality", "warehouse losses", "farmer payment tracking"], compliance: "mandi and GST documentation", icon: "factory" },
  { slug: "real-estate", name: "Real Estate", focus: "developers and property managers", painPoints: ["booking reconciliation", "construction progress tracking", "broker commission disputes"], compliance: "RERA registration workflows", icon: "construction" },
  { slug: "hospitality", name: "Hospitality", focus: "hotels and restaurant groups", painPoints: ["occupancy reporting", "vendor billing", "multi-outlet inventory"], compliance: "FSSAI, GST", icon: "retail" },
  { slug: "banking", name: "Banking & NBFC", focus: "lending and financial services", painPoints: ["loan origination bottlenecks", "KYC document chasing", "collections visibility"], compliance: "RBI-aware audit trails", icon: "retail" },
  { slug: "insurance", name: "Insurance", focus: "brokers and insurers", painPoints: ["policy renewal tracking", "claims document gaps", "agent commission errors"], compliance: "IRDAI-aware documentation", icon: "retail" },
  { slug: "ecommerce", name: "E-commerce", focus: "D2C and marketplace sellers", painPoints: ["order fulfillment errors", "returns processing", "multi-channel inventory sync"], compliance: "GST, consumer protection norms", icon: "retail" },
  { slug: "import-export", name: "Import Export", focus: "trading and export houses", painPoints: ["shipping document errors", "LC reconciliation", "multi-currency invoicing"], compliance: "customs and GST documentation", icon: "logistics" },
  { slug: "warehouse", name: "Warehouse", focus: "warehousing and fulfillment", painPoints: ["pick-path inefficiency", "inventory shrinkage", "3PL billing disputes"], compliance: "GST, e-way bill workflows", icon: "logistics" },
  { slug: "cold-chain", name: "Cold Chain", focus: "cold storage and refrigerated logistics", painPoints: ["temperature excursion tracking", "slot booking conflicts", "energy cost visibility"], compliance: "FSSAI cold chain norms", icon: "logistics" },
  { slug: "packaging", name: "Packaging", focus: "packaging manufacturers", painPoints: ["die inventory tracking", "customer artwork versions", "job scheduling"], compliance: "quality inspection records", icon: "factory" },
  { slug: "rubber", name: "Rubber", focus: "rubber products and tyres components", painPoints: ["compound batch tracking", "curing cycle planning", "quality test records"], compliance: "batch traceability", icon: "factory" },
  { slug: "ceramics", name: "Ceramics", focus: "tiles and sanitaryware", painPoints: ["kiln scheduling", "shade and grade sorting", "export packing lists"], compliance: "quality grading documentation", icon: "factory" },
  { slug: "gems-jewelry", name: "Gems & Jewelry", focus: "diamond and jewelry manufacturing", painPoints: ["job bag tracking", "karat reconciliation", "export invoice accuracy"], compliance: "BIS and export documentation", icon: "retail" },
  { slug: "steel", name: "Steel", focus: "steel fabrication and trading", painPoints: ["weight-based billing errors", "cutting optimization", "dispatch planning"], compliance: "mill certificates, GST", icon: "factory" },
  { slug: "cement", name: "Cement", focus: "cement and building materials", painPoints: ["dealer ledger disputes", "transporter reconciliation", "regional pricing complexity"], compliance: "GST, weighbridge integration", icon: "construction" },
  { slug: "cement-construction-materials", name: "Cement & Construction Materials", focus: "cement plant software and dealer networks", painPoints: ["dispatch gate bottlenecks", "dealer ledger disputes", "production visibility gaps"], compliance: "GST, weighbridge integration", icon: "construction" },
  { slug: "paper", name: "Paper", focus: "paper mills and converters", painPoints: ["roll tracking", "GSM quality variance", "order fulfillment delays"], compliance: "quality test records", icon: "factory" },
  { slug: "printing", name: "Printing", focus: "commercial printing", painPoints: ["plate and die versioning", "color proof approvals", "job costing gaps"], compliance: "client approval audit trails", icon: "factory" },
  { slug: "electronics", name: "Electronics", focus: "EMS and electronics manufacturing", painPoints: ["BOM revision control", "serial number traceability", "RMA tracking"], compliance: "RoHS-style documentation", icon: "factory" },
  { slug: "aerospace", name: "Aerospace Components", focus: "precision aerospace suppliers", painPoints: ["first-article inspection tracking", "material certificates", "strict revision control"], compliance: "AS9100-style traceability", icon: "factory" },
  { slug: "renewable-energy", name: "Renewable Energy", focus: "solar and wind EPC", painPoints: ["project commissioning checklists", "O&M ticket backlog", "spares across sites"], compliance: "project handover documentation", icon: "factory" },
  { slug: "water-treatment", name: "Water Treatment", focus: "water and wastewater plants", painPoints: ["sensor data silos", "chemical dosing logs", "AMC contract tracking"], compliance: "environmental reporting", icon: "factory" },
  { slug: "mining", name: "Mining", focus: "mining and minerals processing", painPoints: ["equipment downtime", "shift production reporting", "safety incident tracking"], compliance: "DGMS-style safety records", icon: "factory" },
  { slug: "agro-processing", name: "Agro Processing", focus: "food and agro mills", painPoints: ["procurement quality variance", "seasonal capacity planning", "mandi reconciliation"], compliance: "FSSAI, GST", icon: "factory" },
  { slug: "dairy", name: "Dairy", focus: "dairy cooperatives and plants", painPoints: ["milk collection reconciliation", "chilling center logistics", "product expiry management"], compliance: "FSSAI, cold chain norms", icon: "factory" },
  { slug: "paint-coatings", name: "Paint & Coatings", focus: "paint and specialty coatings", painPoints: ["formula batch control", "shade matching records", "dealer scheme management"], compliance: "batch traceability, MSDS", icon: "factory" },
];

export const programmaticCities: CityCatalogEntry[] = [
  { slug: "vadodara", name: "Vadodara", state: "Gujarat", insight: "Gujarat industrial hub with manufacturing SMEs adopting ERP and shop-floor apps.", industries: ["Manufacturing", "Chemical", "Pharma"] },
  { slug: "ahmedabad", name: "Ahmedabad", state: "Gujarat", insight: "Fast-growing pharma, textile, and fintech ecosystem in Western India.", industries: ["Pharma", "Textile", "Retail"] },
  { slug: "surat", name: "Surat", state: "Gujarat", insight: "Diamond and textile capital with intense demand for inventory and B2B systems.", industries: ["Textile", "Diamond", "Retail"] },
  { slug: "rajkot", name: "Rajkot", state: "Gujarat", insight: "Auto components and engineering cluster digitizing production tracking.", industries: ["Automotive", "Manufacturing"] },
  { slug: "mumbai", name: "Mumbai", state: "Maharashtra", insight: "Financial capital with enterprise SaaS, fintech, and compliance-heavy software demand.", industries: ["Finance", "Retail", "Logistics"] },
  { slug: "pune", name: "Pune", state: "Maharashtra", insight: "Automotive corridor and IT hub needing enterprise integrations.", industries: ["Automotive", "Manufacturing", "Education"] },
  { slug: "bengaluru", name: "Bengaluru", state: "Karnataka", insight: "India's Silicon Valley for product engineering and AI platforms.", industries: ["SaaS", "Healthcare", "Retail"] },
  { slug: "hyderabad", name: "Hyderabad", state: "Telangana", insight: "Pharma and IT city with regulated industry software needs.", industries: ["Pharma", "Healthcare", "Logistics"] },
  { slug: "chennai", name: "Chennai", state: "Tamil Nadu", insight: "Automotive and manufacturing powerhouse modernizing legacy ERP.", industries: ["Automotive", "Manufacturing", "Logistics"] },
  { slug: "delhi", name: "Delhi NCR", state: "Delhi", insight: "National capital region serving enterprise and consumer brands across North India.", industries: ["Retail", "Education", "Healthcare"] },
  { slug: "jaipur", name: "Jaipur", state: "Rajasthan", insight: "Tourism, gems, and growing IT services demand in Rajasthan.", industries: ["Gems", "Hospitality", "Retail"] },
  { slug: "lucknow", name: "Lucknow", state: "Uttar Pradesh", insight: "Emerging North India hub for government and SME digitization.", industries: ["Education", "Retail", "Healthcare"] },
  { slug: "kanpur", name: "Kanpur", state: "Uttar Pradesh", insight: "Leather and manufacturing cluster needing inventory systems.", industries: ["Manufacturing", "Textile"] },
  { slug: "nagpur", name: "Nagpur", state: "Maharashtra", insight: "Central India logistics hub with warehouse digitization demand.", industries: ["Logistics", "Warehouse"] },
  { slug: "indore", name: "Indore", state: "Madhya Pradesh", insight: "Commercial capital of MP with pharma and FMCG distribution.", industries: ["Pharma", "FMCG", "Retail"] },
  { slug: "bhopal", name: "Bhopal", state: "Madhya Pradesh", insight: "Government and education sector software modernization.", industries: ["Education", "Healthcare"] },
  { slug: "coimbatore", name: "Coimbatore", state: "Tamil Nadu", insight: "Pump and textile manufacturing hub in South India.", industries: ["Manufacturing", "Textile"] },
  { slug: "kochi", name: "Kochi", state: "Kerala", insight: "Port city with logistics and hospitality software needs.", industries: ["Logistics", "Hospitality"] },
  { slug: "visakhapatnam", name: "Visakhapatnam", state: "Andhra Pradesh", insight: "Port and steel city with industrial ERP demand.", industries: ["Steel", "Logistics"] },
  { slug: "patna", name: "Patna", state: "Bihar", insight: "Eastern India growth market for SME ERP and mobile apps.", industries: ["Retail", "Agriculture"] },
  { slug: "ludhiana", name: "Ludhiana", state: "Punjab", insight: "Bicycle and hosiery manufacturing cluster.", industries: ["Manufacturing", "Textile"] },
  { slug: "nashik", name: "Nashik", state: "Maharashtra", insight: "Wine, manufacturing, and auto supplier ecosystem.", industries: ["Manufacturing", "Automotive"] },
  { slug: "ankleshwar", name: "Ankleshwar", state: "Gujarat", insight: "Chemical GIDC with batch manufacturing ERP demand.", industries: ["Chemical", "Pharma"] },
  { slug: "vapi", name: "Vapi", state: "Gujarat", insight: "Pharma and chemical belt on Gujarat-Maharashtra border.", industries: ["Pharma", "Chemical"] },
  { slug: "bharuch", name: "Bharuch", state: "Gujarat", insight: "Petrochemical corridor needing maintenance and batch systems.", industries: ["Chemical", "Energy"] },
  { slug: "dahej", name: "Dahej", state: "Gujarat", insight: "PCPIR chemical zone with process manufacturing focus.", industries: ["Chemical", "Plastics"] },
  { slug: "halol", name: "Halol", state: "Gujarat", insight: "Industrial GIDC near Vadodara with SME manufacturers.", industries: ["Manufacturing", "Automotive"] },
  { slug: "sanand", name: "Sanand", state: "Gujarat", insight: "Auto OEM supplier cluster near Ahmedabad.", industries: ["Automotive", "Manufacturing"] },
  { slug: "pimpri-chinchwad", name: "Pimpri-Chinchwad", state: "Maharashtra", insight: "Auto and engineering hub adjacent to Pune.", industries: ["Automotive", "Manufacturing"] },
  { slug: "thane", name: "Thane", state: "Maharashtra", insight: "Mumbai metro industrial and retail digitization.", industries: ["Retail", "Logistics"] },
  { slug: "gurugram", name: "Gurugram", state: "Haryana", insight: "Corporate HQ hub for enterprise software and SaaS.", industries: ["Finance", "Retail"] },
  { slug: "noida", name: "Noida", state: "Uttar Pradesh", insight: "NCR IT and electronics manufacturing corridor.", industries: ["Electronics", "Retail"] },
  { slug: "faridabad", name: "Faridabad", state: "Haryana", insight: "Auto ancillaries and engineering units in NCR.", industries: ["Automotive", "Manufacturing"] },
  { slug: "mysuru", name: "Mysuru", state: "Karnataka", insight: "Heritage city with growing manufacturing and IT services.", industries: ["Manufacturing", "Education"] },
  { slug: "goa", name: "Goa", state: "Goa", insight: "Hospitality and pharma formulation units.", industries: ["Hospitality", "Pharma"] },
  { slug: "bhubaneswar", name: "Bhubaneswar", state: "Odisha", insight: "Eastern India IT and mining services hub.", industries: ["Mining", "Education"] },
  { slug: "ranchi", name: "Ranchi", state: "Jharkhand", insight: "Mining and steel region digitizing operations.", industries: ["Mining", "Steel"] },
  { slug: "raipur", name: "Raipur", state: "Chhattisgarh", insight: "Steel and rice mill economy needing ERP.", industries: ["Steel", "Agro Processing"] },
  { slug: "amritsar", name: "Amritsar", state: "Punjab", insight: "Textile and food processing in Punjab.", industries: ["Textile", "Food Processing"] },
  { slug: "aurangabad", name: "Aurangabad", state: "Maharashtra", insight: "Auto and pharma cluster in Marathwada.", industries: ["Automotive", "Pharma"] },
  { slug: "kolhapur", name: "Kolhapur", state: "Maharashtra", insight: "Foundry and engineering manufacturing hub.", industries: ["Manufacturing", "Automotive"] },
  { slug: "jamnagar", name: "Jamnagar", state: "Gujarat", insight: "Brass parts and refinery supplier ecosystem.", industries: ["Manufacturing", "Energy"] },
  { slug: "morbi", name: "Morbi", state: "Gujarat", insight: "Ceramic tiles capital of India.", industries: ["Ceramics", "Manufacturing"] },
  { slug: "bhavnagar", name: "Bhavnagar", state: "Gujarat", insight: "Ship breaking and manufacturing on Saurashtra coast.", industries: ["Manufacturing", "Logistics"] },
  { slug: "gandhinagar", name: "Gandhinagar", state: "Gujarat", insight: "Government and IT park hub near Ahmedabad.", industries: ["Education", "Retail"] },
  { slug: "mehsana", name: "Mehsana", state: "Gujarat", insight: "Dairy and agro-processing in North Gujarat.", industries: ["Dairy", "Agriculture"] },
  { slug: "jamshedpur", name: "Jamshedpur", state: "Jharkhand", insight: "Steel city with industrial automation demand.", industries: ["Steel", "Manufacturing"] },
  { slug: "cuttack", name: "Cuttack", state: "Odisha", insight: "Silver filigree and growing SME software market.", industries: ["Retail", "Manufacturing"] },
  { slug: "hubli", name: "Hubli", state: "Karnataka", insight: "North Karnataka commercial hub.", industries: ["Retail", "Agriculture"] },
  { slug: "tiruchirappalli", name: "Tiruchirappalli", state: "Tamil Nadu", insight: "Golden Rock workshop and manufacturing belt.", industries: ["Manufacturing", "Energy"] },
];

export const programmaticCountries: CountryCatalogEntry[] = [
  { slug: "india", name: "India", currency: "INR" },
  { slug: "usa", name: "USA", currency: "USD" },
  { slug: "uk", name: "UK", currency: "GBP" },
  { slug: "uae", name: "UAE", currency: "AED" },
  { slug: "canada", name: "Canada", currency: "CAD" },
  { slug: "australia", name: "Australia", currency: "AUD" },
  { slug: "singapore", name: "Singapore", currency: "USD" },
  { slug: "germany", name: "Germany", currency: "USD" },
];

export const compareTemplates: CompareTemplate[] = [
  { slug: "erp-vs-crm", title: "ERP vs CRM", left: "ERP", right: "CRM", category: "erp", verdict: "ERP runs operations; CRM runs revenue relationships. Most growing manufacturers need both.", leftPros: ["Inventory and production control", "Finance and GST integration", "Single source of operational truth"], rightPros: ["Pipeline and lead tracking", "Sales activity visibility", "Customer communication history"], chooseLeft: "Choose ERP when inventory, production, or finance chaos is the bottleneck.", chooseRight: "Choose CRM when lost leads and poor follow-up block growth." },
  { slug: "custom-erp-vs-sap", title: "Custom ERP vs SAP", left: "Custom ERP", right: "SAP", category: "erp", verdict: "SAP wins at global enterprise scale; custom ERP wins when Indian workflows, GST, and Tally integration matter more than brand.", leftPros: ["Workflow-fit for SME processes", "Lower TCO for 20–200 users", "Full IP ownership"], rightPros: ["Global best practices", "Large partner ecosystem", "Enterprise audit credibility"], chooseLeft: "Choose custom when off-the-shelf SAP modules force expensive workarounds.", chooseRight: "Choose SAP when you need global template rollouts across 500+ users." },
  { slug: "odoo-vs-custom-erp", title: "Odoo vs Custom ERP", left: "Odoo", right: "Custom ERP", category: "erp", verdict: "Odoo is fast to start; custom ERP wins when batch logic, shop-floor mobile, or Tally depth exceeds Odoo limits.", leftPros: ["Quick module activation", "Lower upfront cost", "Community apps"], rightPros: ["Exact workflow match", "No per-user license creep", "Deep Tally/GST customization"], chooseLeft: "Choose Odoo for standard CRM+inventory in year one.", chooseRight: "Choose custom when Odoo customization cost exceeds greenfield build." },
  { slug: "tally-vs-erp-software", title: "Tally vs ERP Software", left: "Tally", right: "ERP Software", category: "erp", verdict: "Tally excels at accounting; ERP adds inventory, production, and operations modules Tally was never designed to run.", leftPros: ["Accountant familiarity", "Low cost for pure accounting", "GST filing workflows"], rightPros: ["Real-time inventory", "Production planning", "Multi-branch operations"], chooseLeft: "Keep Tally when you only need accounting with light inventory.", chooseRight: "Move to ERP when stock, production, or branches outgrow Tally." },
  { slug: "erpnext-vs-odoo", title: "ERPNext vs Odoo", left: "ERPNext", right: "Odoo", category: "erp", verdict: "Both are open-source ERPs; ERPNext suits manufacturing-first teams, Odoo suits broader SMB module needs.", leftPros: ["Manufacturing depth", "Open source", "India community"], rightPros: ["Larger app store", "CRM+website modules", "Faster UI iteration"], chooseLeft: "Evaluate ERPNext for discrete manufacturing BOM depth.", chooseRight: "Evaluate Odoo for retail + CRM + website in one stack." },
  { slug: "sap-vs-odoo", title: "SAP vs Odoo", left: "SAP", right: "Odoo", category: "erp", verdict: "SAP targets enterprise; Odoo targets SMB. Indian mid-market often outgrows Odoo before affording SAP.", leftPros: ["Enterprise governance", "Global rollout", "Audit-grade controls"], rightPros: ["SMB-friendly pricing", "Modular adoption", "Faster implementation"], chooseLeft: "Choose SAP with budget for SI partners and change management.", chooseRight: "Choose Odoo for 10–100 user SMB digitization." },
  { slug: "saas-vs-custom-software", title: "SaaS vs Custom Software", left: "SaaS", right: "Custom Software", category: "strategy", verdict: "SaaS wins on speed; custom wins when workflow uniqueness is your competitive advantage.", leftPros: ["Fast deployment", "Vendor maintains updates", "Predictable subscription"], rightPros: ["Workflow differentiation", "No per-seat tax at scale", "Integration freedom"], chooseLeft: "Choose SaaS when processes are industry-standard.", chooseRight: "Choose custom when software IS the product or process moat." },
  { slug: "zoho-crm-vs-salesforce", title: "Zoho CRM vs Salesforce", left: "Zoho CRM", right: "Salesforce", category: "crm", verdict: "Zoho fits Indian SMB price points; Salesforce fits global enterprise with complex automation.", leftPros: ["India pricing", "Quick setup", "Zoho suite integration"], rightPros: ["Enterprise automation", "AppExchange ecosystem", "Global support"], chooseLeft: "Choose Zoho for 5–50 user sales teams in India.", chooseRight: "Choose Salesforce for global multi-region sales ops." },
  { slug: "zoho-crm-vs-custom-crm", title: "Zoho CRM vs Custom CRM", left: "Zoho CRM", right: "Custom CRM", category: "crm", verdict: "Zoho covers standard sales; custom CRM wins for distributor networks, van sales, and unique approval chains.", leftPros: ["Low subscription", "Mobile app included", "Fast go-live"], rightPros: ["Distributor hierarchy", "Field force offline apps", "ERP integration depth"], chooseLeft: "Choose Zoho for inside sales teams with standard pipelines.", chooseRight: "Choose custom for 500+ distributor networks or complex schemes." },
  { slug: "hubspot-vs-custom-crm", title: "HubSpot vs Custom CRM", left: "HubSpot", right: "Custom CRM", category: "crm", verdict: "HubSpot excels at inbound marketing + CRM; custom fits operational sales in manufacturing and distribution.", leftPros: ["Marketing automation", "Content tools", "SMB-friendly"], rightPros: ["India-specific workflows", "Tally/ERP sync", "Field sales offline"], chooseLeft: "Choose HubSpot for marketing-led B2B SaaS.", chooseRight: "Choose custom for distributor-led Indian B2B." },
  { slug: "offshore-vs-inhouse-development", title: "Offshore vs In-House Development", left: "Offshore (India)", right: "In-House Team", category: "delivery", verdict: "Offshore from India delivers 40–60% cost savings with senior depth; in-house wins when daily on-site pairing is mandatory.", leftPros: ["Senior team depth", "Faster hiring", "Milestone pricing"], rightPros: ["Daily physical access", "Deep domain immersion", "No vendor management"], chooseLeft: "Choose offshore for ERP, mobile, and web product builds.", chooseRight: "Choose in-house when regulatory proximity mandates daily on-site work." },
  { slug: "rpa-vs-custom-automation", title: "RPA vs Custom Automation", left: "RPA Tools", right: "Custom Automation", category: "automation", verdict: "RPA scripts break on UI changes; custom API automation lasts when systems expose stable interfaces.", leftPros: ["Quick screen automation", "No code options", "Pilot in weeks"], rightPros: ["Stable API integrations", "Embedded in ERP", "Lower maintenance"], chooseLeft: "Choose RPA for temporary legacy UI bridging.", chooseRight: "Choose custom when automation is mission-critical long-term." },
  { slug: "custom-software-vs-freelancer", title: "Custom Software Company vs Freelancer", left: "Software Company", right: "Freelancer", category: "delivery", verdict: "Freelancers suit small tasks; companies provide continuity for ERP, compliance, and production systems.", leftPros: ["Team redundancy", "Documented SLAs", "Post-launch support"], rightPros: ["Lower hourly cost", "Flexible for tiny scope", "Direct communication"], chooseLeft: "Choose a company for ERP, CRM, and compliance systems.", chooseRight: "Choose freelancers for landing pages or one-off scripts." },
  { slug: "nextjs-vs-wordpress-business", title: "Next.js vs WordPress for Business", left: "Next.js", right: "WordPress", category: "strategy", verdict: "WordPress suits content blogs; Next.js wins for performance-critical B2B sites that need CRM integration and 95+ CWV.", leftPros: ["Core Web Vitals 95+", "App-like features", "Enterprise security"], rightPros: ["Non-technical editing", "Plugin ecosystem", "Lower initial cost"], chooseLeft: "Choose Next.js for lead-gen sites where speed affects rankings.", chooseRight: "Choose WordPress for content-heavy blogs with frequent non-tech edits." },
  { slug: "flutter-vs-react-native", title: "Flutter vs React Native", left: "Flutter", right: "React Native", category: "strategy", verdict: "Both deliver cross-platform apps; Flutter wins on UI consistency, React Native when team already knows React.", leftPros: ["Pixel-perfect UI", "Single codebase performance", "Growing enterprise adoption"], rightPros: ["React developer pool", "Expo ecosystem", "Web code reuse"], chooseLeft: "Choose Flutter for field apps with offline-first UI.", chooseRight: "Choose React Native when your web team owns mobile too." },
  { slug: "cloud-erp-vs-on-premise-erp", title: "Cloud ERP vs On-Premise ERP", left: "Cloud ERP", right: "On-Premise ERP", category: "erp", verdict: "Cloud ERP reduces IT overhead; on-premise wins only with strict air-gapped compliance requirements.", leftPros: ["No server maintenance", "Automatic backups", "Remote branch access"], rightPros: ["Air-gapped control", "Legacy LAN integrations", "One-time license mindset"], chooseLeft: "Choose cloud for multi-branch Indian SMEs.", chooseRight: "Choose on-premise only with explicit regulatory air-gap needs." },
  { slug: "manufacturing-erp-vs-trading-erp", title: "Manufacturing ERP vs Trading ERP", left: "Manufacturing ERP", right: "Trading ERP", category: "erp", verdict: "Manufacturing ERP needs BOM and shop-floor; trading ERP needs multi-location inventory and scheme management.", leftPros: ["BOM and routing", "Shop-floor tracking", "QC integration"], rightPros: ["Fast inventory turns", "Scheme and discount engines", "Distributor portals"], chooseLeft: "Choose manufacturing ERP for factory-first businesses.", chooseRight: "Choose trading ERP for distribution and import-export." },
  { slug: "salesforce-vs-custom-crm", title: "Salesforce vs Custom CRM", left: "Salesforce", right: "Custom CRM", category: "crm", verdict: "Salesforce suits global enterprise; custom CRM fits Indian distributor models Salesforce configs struggle with.", leftPros: ["Global standard", "AppExchange", "Enterprise reporting"], rightPros: ["Distributor schemes", "GST invoice sync", "Van sales offline"], chooseLeft: "Choose Salesforce for global HQ standardization.", chooseRight: "Choose custom for India-first distribution complexity." },
  { slug: "microsoft-dynamics-vs-custom-erp", title: "Microsoft Dynamics vs Custom ERP", left: "Microsoft Dynamics", right: "Custom ERP", category: "erp", verdict: "Dynamics fits Microsoft-centric enterprises; custom fits Indian manufacturing with Tally and shop-floor mobile.", leftPros: ["Office 365 integration", "Enterprise brand", "Partner network"], rightPros: ["Tally bridge", "Shop-floor Hindi UI", "Lower license stack"], chooseLeft: "Choose Dynamics in Microsoft-heavy global orgs.", chooseRight: "Choose custom for Gujarat/Maharashtra manufacturing SMEs." },
  { slug: "ai-vs-traditional-qc", title: "AI Quality Inspection vs Manual QC", left: "AI Vision QC", right: "Manual QC", category: "automation", verdict: "AI vision scales inspection 24/7; manual QC still needed for tactile and complex judgment calls.", leftPros: ["24/7 inspection", "Defect data analytics", "Consistent standards"], rightPros: ["Tactile checks", "Low tech investment", "Flexible judgment"], chooseLeft: "Choose AI vision for high-volume visual defect detection.", chooseRight: "Keep manual QC for low-volume or tactile quality checks." },
];

export function getServiceByKey(key: string): ServiceCatalogEntry | undefined {
  return programmaticServices.find((s) => s.key === key || s.slug === key);
}

export function getIndustryCatalog(slug: string): IndustryCatalogEntry | undefined {
  return programmaticIndustries.find((i) => i.slug === slug);
}

export function getCityCatalog(slug: string): CityCatalogEntry | undefined {
  return programmaticCities.find((c) => c.slug === slug);
}

const INDUSTRY_NAME_ALIASES: Record<string, string> = {
  diamond: "gems-jewelry",
  saas: "ecommerce",
  finance: "banking",
  "food processing": "food-processing",
  "agro processing": "agro-processing",
};

/** Resolve a city hub industry label to a programmatic industry slug when possible. */
export function resolveIndustrySlug(displayName: string): string | undefined {
  const key = displayName.toLowerCase().trim();
  if (INDUSTRY_NAME_ALIASES[key]) return INDUSTRY_NAME_ALIASES[key];
  const exact = programmaticIndustries.find((i) => i.name.toLowerCase() === key);
  if (exact) return exact.slug;
  const partial = programmaticIndustries.find(
    (i) => i.name.toLowerCase().includes(key) || key.includes(i.slug.replace(/-/g, " ")),
  );
  return partial?.slug;
}
